name: Copy Dist to Dist Branch

on:
  push:
    branches: [main, master]
    paths:
      - 'core/**'

jobs:
  release-to-dist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate release commit and extract version
      id: get_version
      run: |
        COMMIT_MSG="${{ github.event.head_commit.message }}"
        echo "Commit message: $COMMIT_MSG"

        if [[ "$COMMIT_MSG" =~ ^release:\ (v[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
          VERSION="${BASH_REMATCH[1]}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Valid release commit with version: $VERSION"
        else
          echo "Not a release commit. Exiting."
          exit 1
        fi

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Switch to dist branch and clean
      run: |
        if git ls-remote --exit-code --heads origin dist; then
          git checkout dist
        else
          git checkout --orphan dist
        fi

        # Remove all contents
        git rm -rf . > /dev/null 2>&1 || true
        rm -rf * .[^.]* || true

    - name: Copy core/dist to root
      run: |
        cp -r core/dist/* .

    - name: Commit and push to dist
      run: |
        git add .
        git commit -m "Release ${{ steps.get_version.outputs.version }}"
        git push origin dist --force

    - name: Tag dist branch with version
      run: |
        VERSION=${{ steps.get_version.outputs.version }}
        git tag -f "$VERSION"
        git push origin "$VERSION" --force
